
import com.mysql.jdbc.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author 2ndyrGroupB
 */
public class Teachers extends javax.swing.JFrame {

    Connection con = null;
    Statement stmt = null;
    ResultSet rs = null;

    /**
     * Creates new form Teachers
     */
    public Teachers() {
        initComponents();
        con = databaseConnection.connection();
        showTeachers();
        FillCombobox();
        id.setEnabled(false);
        delete.setEnabled(false);
        update.setEnabled(false);

    }

    public ArrayList<Teacher> teachersList() {
        ArrayList<Teacher> teachersList = new ArrayList<>();
        try {

            String query = "SELECT * FROM teacher";
            stmt = con.createStatement();
//                PreparedStatement preparedStmt = con.prepareStatement(query);
            rs = stmt.executeQuery(query);

            Teacher teachers;
            while (rs.next()) {
                teachers = new Teacher(rs.getInt("id"), rs.getInt("teacher_id"), rs.getString("teacherName"), rs.getString("courseGroupAssign"));
                teachersList.add(teachers);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return teachersList;
    }

    public void showTeachers() {
        ArrayList<Teacher> list = teachersList();
        DefaultTableModel model = (DefaultTableModel) tableTeacher.getModel();
        Object[] row = new Object[4];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getId();
            row[1] = list.get(i).getTeacher_id();
            row[2] = list.get(i).getTeacherName();
            row[3] = list.get(i).getCourseGroupAssign();

            model.addRow(row);
        }
    }

    private void FillCombobox() {
        try {
            String sql = "SELECT * FROM course";
            PreparedStatement preparedStmt = con.prepareStatement(sql);
            rs = preparedStmt.executeQuery();

            while (rs.next()) {
                String courseGroup = rs.getString("courseGroup");
                groupCourse.addItem(courseGroup);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTeacher = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        mainMenu = new javax.swing.JButton();
        teacherManage = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        teacher_id = new javax.swing.JTextField();
        tName = new javax.swing.JLabel();
        inputTname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        reset = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        update = new javax.swing.JButton();
        groupCourse = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableTeacher.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Teacher ID", "Teacher Name", "CourseGroup Assign"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableTeacher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTeacherMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableTeacher);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 460, 380));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Teachers Lists");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, -1, -1));

        mainMenu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mainMenu.setText("> Main Menu");
        mainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuActionPerformed(evt);
            }
        });
        jPanel1.add(mainMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, -1, -1));

        teacherManage.setFont(new java.awt.Font("Bookman Old Style", 3, 18)); // NOI18N
        teacherManage.setText("Teacher Management ");
        jPanel1.add(teacherManage, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("ID:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 140, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Teacher ID:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        teacher_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                teacher_idKeyReleased(evt);
            }
        });
        jPanel1.add(teacher_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 140, 30));

        tName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tName.setText("Teacher Name:");
        jPanel1.add(tName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        inputTname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputTnameKeyReleased(evt);
            }
        });
        jPanel1.add(inputTname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 140, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Course Group Assign:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        reset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel1.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, -1, -1));

        submit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        submit.setText("Add");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel1.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 80, -1));

        delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, -1, -1));

        update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, -1, -1));

        groupCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        groupCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupCourseActionPerformed(evt);
            }
        });
        jPanel1.add(groupCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 140, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\2ndyrGroupB\\Desktop\\JudyFinalProjectJava\\SchoolManagementSystem\\school5.png")); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        try {
          
            String query = "INSERT INTO teacher(teacher_id,teacherName,courseGroupAssign)VALUES(?,?,?)";
            PreparedStatement preparedStmt = con.prepareStatement(query);
            int teacherID = Integer.parseInt(teacher_id.getText());

            preparedStmt.setInt(1, teacherID);
            preparedStmt.setString(2, inputTname.getText());
            String course = groupCourse.getSelectedItem().toString();

            preparedStmt.setString(3, course);

            preparedStmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Added SUCESSFULLY!");
            DefaultTableModel model = (DefaultTableModel) tableTeacher.getModel();
            model.setRowCount(0);
            showTeachers();
            submit.setEnabled(false);
//            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }


    }//GEN-LAST:event_submitActionPerformed

    private void mainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Menu menu = new Menu();
        menu.setVisible(true);
    }//GEN-LAST:event_mainMenuActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        try {

            int row = tableTeacher.getSelectedRow();
            String value = (tableTeacher.getModel().getValueAt(row, 0).toString());
            String query = "UPDATE teacher SET teacher_id= ?, teacherName = ?,courseGroupAssign = ? WHERE id = " + value;

            PreparedStatement preparedStmt = con.prepareStatement(query);

            preparedStmt.setString(1, teacher_id.getText());
            preparedStmt.setString(2, inputTname.getText());
            String course = groupCourse.getSelectedItem().toString();

            preparedStmt.setString(3, course);

            preparedStmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Updated SUCESSFULLY!");
            DefaultTableModel model = (DefaultTableModel) tableTeacher.getModel();
            model.setRowCount(0);
            showTeachers();
             update.setEnabled(false);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }


    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        int opt = JOptionPane.showConfirmDialog(null, "Are you sure to Delete", "Delete", JOptionPane.YES_NO_OPTION);
        if (opt == 0) {
            try {
             
                int row = tableTeacher.getSelectedRow();
                String Id = id.getText();

                String query = "DELETE FROM teacher WHERE id = " + Id;
                PreparedStatement preparedStmt = con.prepareStatement(query);
                stmt.executeUpdate(query);
                DefaultTableModel model = (DefaultTableModel) tableTeacher.getModel();
                model.setRowCount(0);
                showTeachers();
                 delete.setEnabled(false);

                JOptionPane.showMessageDialog(null, "Deleted SUCESSFULLY!");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }

    }//GEN-LAST:event_deleteActionPerformed

    private void tableTeacherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTeacherMouseClicked

        int i = tableTeacher.getSelectedRow();
        TableModel model = tableTeacher.getModel();
        id.setText(model.getValueAt(i, 0).toString());
        teacher_id.setText(model.getValueAt(i, 1).toString());
        inputTname.setText(model.getValueAt(i, 2).toString());
        groupCourse.setSelectedItem(model.getValueAt(i, 3).toString());
        delete.setEnabled(true);
        update.setEnabled(false);
        submit.setEnabled(false);
    }//GEN-LAST:event_tableTeacherMouseClicked

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        id.setText("");
        inputTname.setText("");
        teacher_id.setText("");
        groupCourse.setSelectedIndex(0);
        submit.setEnabled(true);
        delete.setEnabled(false);
        update.setEnabled(false);
    }//GEN-LAST:event_resetActionPerformed

    private void teacher_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teacher_idKeyReleased
     
        update.setEnabled(true);
        delete.setEnabled(false);
    }//GEN-LAST:event_teacher_idKeyReleased

    private void inputTnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputTnameKeyReleased
        update.setEnabled(true);
        delete.setEnabled(false);
    }//GEN-LAST:event_inputTnameKeyReleased

    private void groupCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupCourseActionPerformed
        update.setEnabled(true);
        delete.setEnabled(false);
    }//GEN-LAST:event_groupCourseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teachers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teachers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teachers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teachers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teachers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delete;
    private javax.swing.JComboBox<String> groupCourse;
    private javax.swing.JTextField id;
    private javax.swing.JTextField inputTname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mainMenu;
    private javax.swing.JButton reset;
    private javax.swing.JButton submit;
    private javax.swing.JLabel tName;
    private javax.swing.JTable tableTeacher;
    private javax.swing.JLabel teacherManage;
    private javax.swing.JTextField teacher_id;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables

}
